#Ansible Playbook to deploy to Tomcat Docker container and restart tomcat:
- hosts: jenkins
  become: true
  become_method: sudo

  tasks:
  - name: build maven
    shell: /var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/maven/bin/mvn clean install

  #- name: Pull and run Tomcat
  #  shell: "docker run -p 8888:8080 -v /usr/src/war:/usr/local/tomcat/webapps tomcat:9.0 &"