---
#Ansible Playbook to deploy to Tomcat Docker container and restart tomcat:
- hosts: tomcat
  become: true
  become_method: sudo

  tasks:
  - name: Deploy WAR file
    ansible.builtin.copy:
      src: ./target/maven-web-application.war
      dest: /usr/src/war/app.war

  - name: Stopping the Tomcat container
    shell: systemctl restart docker

